lookahead_distance: 0.4 # The distance to look ahead (in meters) for path planning.
speed: 0.5 # The maximum speed of the robot (in meters per second).
expansion_size: 6 # The factor by which obstacles are expanded during path planning.
target_error: 0.4 # The acceptable error margin (in meters) for reaching the target location.
robot_r: 0.4 # The safety distance around the robot (in meters) for local obstacle avoidance.